name: Deploy to dev
on:
  push:
    branches: 
      - "main"
jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploy everything to dev clusters
    steps:
      - name: SSH into server
        run: |
          echo "hi there"